version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - 3306:3306
    volumes: 
      - /var/lib/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: website
    restart: always
  server:
    image: image:1.0.5
    container_name: server
    depends_on:
      - mysql
    ports: 
      - 80:80
    restart: always
